# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('lora-mesh-example', ['lora-mesh'])
    obj.source = 'lora-mesh-example.cc'

    obj2 = bld.create_ns3_program('urban-scenario-example', ['lora-mesh'])
    obj2.source = 'urban-scenario-example.cc'
