# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('animal-tracking-scenario-example', ['lora-mesh'])
    obj.source = 'animal-tracking-scenario-example.cc'

    obj = bld.create_ns3_program('urban-scenario-example', ['lora-mesh'])
    obj.source = 'urban-scenario-example.cc'
